### ISSUE TITLE
Prebuild React and React-Native dependencies

### ISSUE THREAD

**Issue by zamotany** [callstack/haul#174]
In order to improve build times we could extract `react` and `react-native` depdencies into [DLL](https://webpack.js.org/plugins/dll-plugin/) and provide a way for user to add their own depednecies to this bundle. However, this solution will split code into 2 files, so unless there's an option to load multiple filesin RN app, we can't benefit from it.

**Comment by satya164** [comment]
I had a little chat about it with some folks earlier:
- There's a feature called unbundle (it's completely undocumented, so not sure how it works), which can split the code into multiple bundles for faster startup
- JSC allows to synchronously load additional bundles which unbundle uses (that's why FB has a fork of JSC, to add this feature), but doesn't support loading bundles asynchronously

**Comment by sdyxch** [comment]
when will you support the feature for webpack-dll😝

**Comment by bakso** [comment]
+1

**Comment by thymikee** [comment]
We'd appreciate some help on that, so if someone is interesting in investigating whether this solution is actually faster (we'd need to concat the dll bundle with regular one somehow), come on in!

**Comment by sdyxch** [comment]
For iOS, use the method loadSourceForBridge in RCTBridgeDelegate, I tried load dll-bundle from local first, then load regular-bundle from network, and concat the dll-one with the regular-one, it works

**Comment by zamotany** [comment]
There's an ongoing effort to bring multi-bundle support to RN and Haul already allows to generate multiple bunndles, so this issue is irrelevant. Once we get to more usable state, the docs will have more info on the topic.
