### ISSUE TITLE
Remove haul

### ISSUE THREAD

**Issue by KasparasGud** [callstack/haul#396]
Sorry if this was answered somewhere else but are there instructions available on how to safely remove haul from your project and switch back to default CLI tools ?

Thank you

**Comment by thymikee** [comment]
We don't provide an automatic way to do so. If you use your git wisely, you should be able to just revert the commit. If not, you'll need to revert the init steps by hand (see what changes on a fresh RN project).

**Comment by vzaffalon** [comment]
wow that is horrible

**Comment by FredyC** [comment]
@vzaffalon Really? How many OS tools provide means for removing it? Look at React Native itself, once you add some native module, it's impossible to remove it automatically, you always have to trace back (unless well versioned with Git).

What about giving try to what @thymikee said and then you can document your finding instead of just complaining ;)

**Comment by vzaffalon** [comment]
React native is a big mess, doesnt mean you also have to be, it is easier to atack me or put the fault in my git abilities then accepting the true, good luck going foward.

**Comment by vzaffalon** [comment]
wow thanks for the git class

**Comment by satya164** [comment]
@vzaffalon go away dude.
