### ISSUE TITLE
RAM bundles

### ISSUE THREAD

**Issue by adgarcia** [callstack/haul#553]
## What flag do I need to flip to get to RN to properly parse the ram bundle generated by haul?

So, I yanked your ram bundle plugin out of the `next` branch and just optimistically passed it as a webpack plugin to my haul build script (which uses 'old' haul @ r.c.14) ... and it works! Sort of! I sanity checked the bundle using Facebook's `RamBundleParser`, and that went swimmingly (`parser.getStartupCode()` and `parser.getModule(n)` both printed out a lot of bundled javascript in the format one would expect). However, the app red-screens on launch because (I think) I need to tell RN to expect a RAM bundle.

Would you all happen to know what flag I need to flip to get the bundle to be correctly parsed?

**Comment by zamotany** [comment]
Normally, to enable RAM bundles, you have to modify build configs in XCode/Gradle: https://facebook.github.io/react-native/docs/performance#ram-bundles-inline-requires

However, do check whether bundle is a RAM bundle, React Native internally check if the bundle starts with `MAGIC_NUMBER`. So if you build Index RAM bundle for iOS it should work just fine. For Android, we are working on File RAM bundle, which is the default RAM bundle format for Android. Index RAM bundle for Android are currently broken. We are also investigating that, but the issue is caused by React Native (Android).

So:
* if you want Index RAM bundle on iOS - it should work
* if you want Index RAM bundle on Android - it's broken
* if you want File RAM bundle on Android - we are working on it

Hope that helps

**Comment by adgarcia** [comment]
Thanks, that was helpful. Does haul provide a way to preload modules? This is possible using metro:

```JavaScript
const modulePaths = require('./packager/modulePaths');
const resolve = require('path').resolve;
const fs = require('fs');

// Update the following line if the root folder of your app is somewhere else.
const ROOT_FOLDER = resolve(__dirname, '..');

const config = {
  transformer: {
    getTransformOptions: () => {
      const moduleMap = {};
      modulePaths.forEach(path => {
        if (fs.existsSync(path)) {
          moduleMap[resolve(path)] = true;
        }
      });
      return {
        preloadedModules: moduleMap,
        transform: { inlineRequires: { blacklist: moduleMap } },
      };
    },
  },
  projectRoot:ROOT_FOLDER,
};

module.exports = config;
```

Does haul have an equivalent?

**Comment by zamotany** [comment]
@adgarcia No, we don't support that. However, there is ongoing work to add support for DLL bundles to both Haul and React Native, so it is possible that in the future, you would be able preload some code.
