### ISSUE TITLE
What does the multi-bundle command do?

### ISSUE THREAD

**Issue by salomaosnff** [callstack/haul#618]
## Ask your Question
When you run the haul --help command, a multi-bundle command is listed. Your description is a bit vague, what would be multi-bundle mode? How is the conventional bundle different?
Reading the CLI documentation I found nothing about.

**Comment by zamotany** [comment]
This command uses Webpack's DLL feature to build offload shared/common dependencies to DLL bundle. Additionally there are app bundles which use this DLL bundle(s).

This is a not-yet-usable feature in Haul connected with this proposal: https://github.com/react-native-community/discussions-and-proposals/issues/127

As of right now, there's no point in using it unless, you're running special forked version of RN like this one: https://github.com/callstack/react-native/tree/feat/apennine-0.60 . Because of that there is no documentation for it.

We are trying to get support for multiple-bundle merged into the core of RN, so stay tuned.
