### ISSUE TITLE
How to use multi-bundle?

### ISSUE THREAD

**Issue by xuyuanxiang** [callstack/haul#744]
## How to use `haul multi-bundle` ?

![](https://cdn.xuyuanxiang.me/ios_build_config_7e22a742.png)

Using  haul multi-bundle with `features.multiBundle: 2` was successfully completed.

But RN require a `main.jsbundle` file:

![](https://cdn.xuyuanxiang.me/react-native-xcode-sh_d12e64e8.png)

```console
done ▶︎ Built successfully in 0.75s!
done ▶︎ All bundles successfully compiled. You can now run your React Native multi-bundle app.

+ [[ false != true ]]
+ [[ ! -f /Users/xuyuanxiang/Library/Developer/Xcode/DerivedData/UMIHaulExample-faqwvjyrvbsxfnckuzljqljoxaap/Build/Products/Release-iphoneos/UMIHaulExample.app/main.jsbundle ]]
+ echo 'error: File /Users/xuyuanxiang/Library/Developer/Xcode/DerivedData/UMIHaulExample-faqwvjyrvbsxfnckuzljqljoxaap/Build/Products/Release-iphoneos/UMIHaulExample.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/xuyuanxiang/Library/Developer/Xcode/DerivedData/UMIHaulExample-faqwvjyrvbsxfnckuzljqljoxaap/Build/Products/Release-iphoneos/UMIHaulExample.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2

```

**Comment by zamotany** [comment]
You can find the complete example (that's working) here: https://github.com/react-native-community/react-native-multibundle/tree/master/Example

To answer your question, the code that loads the bundle can be instructed to load different one than `main.jsbundle` like here: https://github.com/react-native-community/react-native-multibundle/blob/master/Example/ios/Example/AppDelegate.m#L41

Keep in mind that to use multibundle feature you would need to use `callstack/react-native#feat/bundle-id-for-multibundle` fork of React Native, since the PRs to bring mutlibundle support are not yet merged. Additionally you would need to add `react-native-multibundle` native module and write a code that would call `loadBundle` etc so the bundle management is on your side.
